// This file is generated by rust-protobuf 2.18.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `chain/ledger.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_2;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct LedgerConfig {
    // message fields
    pub ledger: ::protobuf::SingularPtrField<Ledger>,
    pub signet: ::protobuf::SingularPtrField<super::sign::Signet>,
    pub signet_pre: ::protobuf::SingularPtrField<super::sign::Signet>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a LedgerConfig {
    fn default() -> &'a LedgerConfig {
        <LedgerConfig as ::protobuf::Message>::default_instance()
    }
}

impl LedgerConfig {
    pub fn new() -> LedgerConfig {
        ::std::default::Default::default()
    }

    // .chain.Ledger ledger = 1;


    pub fn get_ledger(&self) -> &Ledger {
        self.ledger.as_ref().unwrap_or_else(|| <Ledger as ::protobuf::Message>::default_instance())
    }
    pub fn clear_ledger(&mut self) {
        self.ledger.clear();
    }

    pub fn has_ledger(&self) -> bool {
        self.ledger.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ledger(&mut self, v: Ledger) {
        self.ledger = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ledger(&mut self) -> &mut Ledger {
        if self.ledger.is_none() {
            self.ledger.set_default();
        }
        self.ledger.as_mut().unwrap()
    }

    // Take field
    pub fn take_ledger(&mut self) -> Ledger {
        self.ledger.take().unwrap_or_else(|| Ledger::new())
    }

    // .chain.Signet signet = 2;


    pub fn get_signet(&self) -> &super::sign::Signet {
        self.signet.as_ref().unwrap_or_else(|| <super::sign::Signet as ::protobuf::Message>::default_instance())
    }
    pub fn clear_signet(&mut self) {
        self.signet.clear();
    }

    pub fn has_signet(&self) -> bool {
        self.signet.is_some()
    }

    // Param is passed by value, moved
    pub fn set_signet(&mut self, v: super::sign::Signet) {
        self.signet = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signet(&mut self) -> &mut super::sign::Signet {
        if self.signet.is_none() {
            self.signet.set_default();
        }
        self.signet.as_mut().unwrap()
    }

    // Take field
    pub fn take_signet(&mut self) -> super::sign::Signet {
        self.signet.take().unwrap_or_else(|| super::sign::Signet::new())
    }

    // .chain.Signet signet_pre = 3;


    pub fn get_signet_pre(&self) -> &super::sign::Signet {
        self.signet_pre.as_ref().unwrap_or_else(|| <super::sign::Signet as ::protobuf::Message>::default_instance())
    }
    pub fn clear_signet_pre(&mut self) {
        self.signet_pre.clear();
    }

    pub fn has_signet_pre(&self) -> bool {
        self.signet_pre.is_some()
    }

    // Param is passed by value, moved
    pub fn set_signet_pre(&mut self, v: super::sign::Signet) {
        self.signet_pre = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signet_pre(&mut self) -> &mut super::sign::Signet {
        if self.signet_pre.is_none() {
            self.signet_pre.set_default();
        }
        self.signet_pre.as_mut().unwrap()
    }

    // Take field
    pub fn take_signet_pre(&mut self) -> super::sign::Signet {
        self.signet_pre.take().unwrap_or_else(|| super::sign::Signet::new())
    }
}

impl ::protobuf::Message for LedgerConfig {
    fn is_initialized(&self) -> bool {
        for v in &self.ledger {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.signet {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.signet_pre {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.ledger)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.signet)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.signet_pre)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.ledger.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.signet.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.signet_pre.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.ledger.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.signet.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.signet_pre.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> LedgerConfig {
        LedgerConfig::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Ledger>>(
                "ledger",
                |m: &LedgerConfig| { &m.ledger },
                |m: &mut LedgerConfig| { &mut m.ledger },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::sign::Signet>>(
                "signet",
                |m: &LedgerConfig| { &m.signet },
                |m: &mut LedgerConfig| { &mut m.signet },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::sign::Signet>>(
                "signet_pre",
                |m: &LedgerConfig| { &m.signet_pre },
                |m: &mut LedgerConfig| { &mut m.signet_pre },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<LedgerConfig>(
                "LedgerConfig",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static LedgerConfig {
        static instance: ::protobuf::rt::LazyV2<LedgerConfig> = ::protobuf::rt::LazyV2::INIT;
        instance.get(LedgerConfig::new)
    }
}

impl ::protobuf::Clear for LedgerConfig {
    fn clear(&mut self) {
        self.ledger.clear();
        self.signet.clear();
        self.signet_pre.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for LedgerConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LedgerConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct Ledger {
    // message fields
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    pub description: ::std::string::String,
    pub organization_policies: ::protobuf::RepeatedField<super::organization::OrganizationPolicy>,
    pub foundation: ::protobuf::SingularPtrField<super::policy::Foundation>,
    pub policy: super::policy::Policy,
    pub upgrade_policy: ::protobuf::SingularPtrField<super::policy::UpgradePolicy>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Ledger {
    fn default() -> &'a Ledger {
        <Ledger as ::protobuf::Message>::default_instance()
    }
}

impl Ledger {
    pub fn new() -> Ledger {
        ::std::default::Default::default()
    }

    // string id = 1;


    pub fn get_id(&self) -> &str {
        &self.id
    }
    pub fn clear_id(&mut self) {
        self.id.clear();
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: ::std::string::String) {
        self.id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_id(&mut self) -> &mut ::std::string::String {
        &mut self.id
    }

    // Take field
    pub fn take_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.id, ::std::string::String::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // string description = 3;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }

    // repeated .chain.OrganizationPolicy organization_policies = 4;


    pub fn get_organization_policies(&self) -> &[super::organization::OrganizationPolicy] {
        &self.organization_policies
    }
    pub fn clear_organization_policies(&mut self) {
        self.organization_policies.clear();
    }

    // Param is passed by value, moved
    pub fn set_organization_policies(&mut self, v: ::protobuf::RepeatedField<super::organization::OrganizationPolicy>) {
        self.organization_policies = v;
    }

    // Mutable pointer to the field.
    pub fn mut_organization_policies(&mut self) -> &mut ::protobuf::RepeatedField<super::organization::OrganizationPolicy> {
        &mut self.organization_policies
    }

    // Take field
    pub fn take_organization_policies(&mut self) -> ::protobuf::RepeatedField<super::organization::OrganizationPolicy> {
        ::std::mem::replace(&mut self.organization_policies, ::protobuf::RepeatedField::new())
    }

    // .chain.Foundation foundation = 5;


    pub fn get_foundation(&self) -> &super::policy::Foundation {
        self.foundation.as_ref().unwrap_or_else(|| <super::policy::Foundation as ::protobuf::Message>::default_instance())
    }
    pub fn clear_foundation(&mut self) {
        self.foundation.clear();
    }

    pub fn has_foundation(&self) -> bool {
        self.foundation.is_some()
    }

    // Param is passed by value, moved
    pub fn set_foundation(&mut self, v: super::policy::Foundation) {
        self.foundation = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_foundation(&mut self) -> &mut super::policy::Foundation {
        if self.foundation.is_none() {
            self.foundation.set_default();
        }
        self.foundation.as_mut().unwrap()
    }

    // Take field
    pub fn take_foundation(&mut self) -> super::policy::Foundation {
        self.foundation.take().unwrap_or_else(|| super::policy::Foundation::new())
    }

    // .chain.Policy policy = 6;


    pub fn get_policy(&self) -> super::policy::Policy {
        self.policy
    }
    pub fn clear_policy(&mut self) {
        self.policy = super::policy::Policy::Any;
    }

    // Param is passed by value, moved
    pub fn set_policy(&mut self, v: super::policy::Policy) {
        self.policy = v;
    }

    // .chain.UpgradePolicy upgrade_policy = 7;


    pub fn get_upgrade_policy(&self) -> &super::policy::UpgradePolicy {
        self.upgrade_policy.as_ref().unwrap_or_else(|| <super::policy::UpgradePolicy as ::protobuf::Message>::default_instance())
    }
    pub fn clear_upgrade_policy(&mut self) {
        self.upgrade_policy.clear();
    }

    pub fn has_upgrade_policy(&self) -> bool {
        self.upgrade_policy.is_some()
    }

    // Param is passed by value, moved
    pub fn set_upgrade_policy(&mut self, v: super::policy::UpgradePolicy) {
        self.upgrade_policy = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_upgrade_policy(&mut self) -> &mut super::policy::UpgradePolicy {
        if self.upgrade_policy.is_none() {
            self.upgrade_policy.set_default();
        }
        self.upgrade_policy.as_mut().unwrap()
    }

    // Take field
    pub fn take_upgrade_policy(&mut self) -> super::policy::UpgradePolicy {
        self.upgrade_policy.take().unwrap_or_else(|| super::policy::UpgradePolicy::new())
    }
}

impl ::protobuf::Message for Ledger {
    fn is_initialized(&self) -> bool {
        for v in &self.organization_policies {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.foundation {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.upgrade_policy {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.organization_policies)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.foundation)?;
                },
                6 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.policy, 6, &mut self.unknown_fields)?
                },
                7 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.upgrade_policy)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.description);
        }
        for value in &self.organization_policies {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let Some(ref v) = self.foundation.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.policy != super::policy::Policy::Any {
            my_size += ::protobuf::rt::enum_size(6, self.policy);
        }
        if let Some(ref v) = self.upgrade_policy.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.description.is_empty() {
            os.write_string(3, &self.description)?;
        }
        for v in &self.organization_policies {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let Some(ref v) = self.foundation.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.policy != super::policy::Policy::Any {
            os.write_enum(6, ::protobuf::ProtobufEnum::value(&self.policy))?;
        }
        if let Some(ref v) = self.upgrade_policy.as_ref() {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Ledger {
        Ledger::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "id",
                |m: &Ledger| { &m.id },
                |m: &mut Ledger| { &mut m.id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &Ledger| { &m.name },
                |m: &mut Ledger| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &Ledger| { &m.description },
                |m: &mut Ledger| { &mut m.description },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::organization::OrganizationPolicy>>(
                "organization_policies",
                |m: &Ledger| { &m.organization_policies },
                |m: &mut Ledger| { &mut m.organization_policies },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::policy::Foundation>>(
                "foundation",
                |m: &Ledger| { &m.foundation },
                |m: &mut Ledger| { &mut m.foundation },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::policy::Policy>>(
                "policy",
                |m: &Ledger| { &m.policy },
                |m: &mut Ledger| { &mut m.policy },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::policy::UpgradePolicy>>(
                "upgrade_policy",
                |m: &Ledger| { &m.upgrade_policy },
                |m: &mut Ledger| { &mut m.upgrade_policy },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Ledger>(
                "Ledger",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Ledger {
        static instance: ::protobuf::rt::LazyV2<Ledger> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Ledger::new)
    }
}

impl ::protobuf::Clear for Ledger {
    fn clear(&mut self) {
        self.id.clear();
        self.name.clear();
        self.description.clear();
        self.organization_policies.clear();
        self.foundation.clear();
        self.policy = super::policy::Policy::Any;
        self.upgrade_policy.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Ledger {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Ledger {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12chain/ledger.proto\x12\x05chain\x1a\x18chain/organization.proto\
    \x1a\x12chain/policy.proto\x1a\x10chain/sign.proto\"\x8a\x01\n\x0cLedger\
    Config\x12%\n\x06ledger\x18\x01\x20\x01(\x0b2\r.chain.LedgerR\x06ledger\
    \x12%\n\x06signet\x18\x02\x20\x01(\x0b2\r.chain.SignetR\x06signet\x12,\n\
    \nsignet_pre\x18\x03\x20\x01(\x0b2\r.chain.SignetR\tsignetPre\"\xb5\x02\
    \n\x06Ledger\x12\x0e\n\x02id\x18\x01\x20\x01(\tR\x02id\x12\x12\n\x04name\
    \x18\x02\x20\x01(\tR\x04name\x12\x20\n\x0bdescription\x18\x03\x20\x01(\t\
    R\x0bdescription\x12N\n\x15organization_policies\x18\x04\x20\x03(\x0b2\
    \x19.chain.OrganizationPolicyR\x14organizationPolicies\x121\n\nfoundatio\
    n\x18\x05\x20\x01(\x0b2\x11.chain.FoundationR\nfoundation\x12%\n\x06poli\
    cy\x18\x06\x20\x01(\x0e2\r.chain.PolicyR\x06policy\x12;\n\x0eupgrade_pol\
    icy\x18\x07\x20\x01(\x0b2\x14.chain.UpgradePolicyR\rupgradePolicyBR\n\
    \x20cn.aberic.george.protocols.chainB\x0bLedgerProtoZ!github.com/george/\
    protocols/chainb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
