[workspace]
members = [
    "george-client",
    "george-comm",
    "george-db",
    "george-deploy",
    "george-examples",
    "george-ge",
    "george-log",
    "george-rpc",
    "george-server",
]