// This file is generated by rust-protobuf 2.18.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `db/service.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_2;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10db/service.proto\x12\x02db\x1a\rdb/user.proto\x1a\rdb/page.proto\
    \x1a\x11db/database.proto\x1a\rdb/view.proto\x1a\x0edb/index.proto\x1a\r\
    db/disk.proto\x1a\x0fdb/memory.proto\x1a\x12comm/request.proto\x1a\x13co\
    mm/response.proto28\n\x0bUserService\x12)\n\x05login\x12\x10.db.RequestL\
    ogin\x1a\x0e.comm.Response2\xf8\x01\n\x0bPageService\x12#\n\x04list\x12\
    \r.comm.Request\x1a\x0c.db.PageList\x12/\n\x06create\x12\x15.db.RequestP\
    ageCreate\x1a\x0e.comm.Response\x12/\n\x06modify\x12\x15.db.RequestPageM\
    odify\x1a\x0e.comm.Response\x121\n\x04info\x12\x13.db.RequestPageInfo\
    \x1a\x14.db.ResponsePageInfo\x12/\n\x06remove\x12\x15.db.RequestPageRemo\
    ve\x1a\x0e.comm.Response2\x94\x02\n\x0fDatabaseService\x12'\n\x04list\
    \x12\r.comm.Request\x1a\x10.db.DatabaseList\x123\n\x06create\x12\x19.db.\
    RequestDatabaseCreate\x1a\x0e.comm.Response\x123\n\x06modify\x12\x19.db.\
    RequestDatabaseModify\x1a\x0e.comm.Response\x129\n\x04info\x12\x17.db.Re\
    questDatabaseInfo\x1a\x18.db.ResponseDatabaseInfo\x123\n\x06remove\x12\
    \x19.db.RequestDatabaseRemove\x1a\x0e.comm.Response2\xa6\x03\n\x0bViewSe\
    rvice\x12)\n\x04list\x12\x13.db.RequestViewList\x1a\x0c.db.ViewList\x12/\
    \n\x06create\x12\x15.db.RequestViewCreate\x1a\x0e.comm.Response\x12/\n\
    \x06modify\x12\x15.db.RequestViewModify\x1a\x0e.comm.Response\x121\n\x04\
    info\x12\x13.db.RequestViewInfo\x1a\x14.db.ResponseViewInfo\x12/\n\x06re\
    move\x12\x15.db.RequestViewRemove\x1a\x0e.comm.Response\x121\n\x07archiv\
    e\x12\x16.db.RequestViewArchive\x1a\x0e.comm.Response\x127\n\x06record\
    \x12\x15.db.RequestViewRecord\x1a\x16.db.ResponseViewRecord\x12:\n\x07re\
    cords\x12\x16.db.RequestViewRecords\x1a\x17.db.ResponseViewRecords2\xa2\
    \x01\n\x0cIndexService\x12+\n\x04list\x12\x14.db.RequestIndexList\x1a\r.\
    db.IndexList\x120\n\x06create\x12\x16.db.RequestIndexCreate\x1a\x0e.comm\
    .Response\x123\n\x04info\x12\x14.db.RequestIndexInfo\x1a\x15.db.Response\
    IndexInfo2\xf2\x02\n\x0bDiskService\x12*\n\x03put\x12\x13.db.RequestDisk\
    Into\x1a\x0e.comm.Response\x12*\n\x03set\x12\x13.db.RequestDiskInto\x1a\
    \x0e.comm.Response\x12.\n\x03get\x12\x12.db.RequestDiskOut\x1a\x13.db.Re\
    sponseDiskOut\x128\n\x0cget_by_index\x12\x13.db.RequestDiskIOut\x1a\x13.\
    db.ResponseDiskOut\x12/\n\x06remove\x12\x15.db.RequestDiskRemove\x1a\x0e\
    .comm.Response\x127\n\x06select\x12\x15.db.RequestDiskSelect\x1a\x16.db.\
    ResponseDiskSelect\x127\n\x06delete\x12\x15.db.RequestDiskDelete\x1a\x16\
    .db.ResponseDiskDelete2\xba\x03\n\rMemoryService\x12,\n\x03put\x12\x15.d\
    b.RequestMemoryInto\x1a\x0e.comm.Response\x12,\n\x03set\x12\x15.db.Reque\
    stMemoryInto\x1a\x0e.comm.Response\x122\n\x03get\x12\x14.db.RequestMemor\
    yOut\x1a\x15.db.ResponseMemoryOut\x121\n\x06remove\x12\x17.db.RequestMem\
    oryRemove\x1a\x0e.comm.Response\x125\n\x0bput_by_page\x12\x16.db.Request\
    MemoryPInto\x1a\x0e.comm.Response\x125\n\x0bset_by_page\x12\x16.db.Reque\
    stMemoryPInto\x1a\x0e.comm.Response\x12<\n\x0bget_by_page\x12\x15.db.Req\
    uestMemoryPOut\x1a\x16.db.ResponseMemoryPOut\x12:\n\x0eremove_by_page\
    \x12\x18.db.RequestMemoryPRemove\x1a\x0e.comm.ResponseBM\n\x1dcn.aberic.\
    george.protocols.dbB\x0cServiceProtoZ\x1egithub.com/george/protocols/dbb\
    \x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
